### PR TITLE
Add ability to skip hashing if the users know what they are doing

### PR DESCRIPTION
**Pull request by Kuree**
The new hashing mechanism takes a lot of time in the profiling. This PR allows advanced users to skip hashing during `wire` process to significantly speed up the circuit creation process.

This PR reduces the garnet creation time by 10s when applied to `canal`.

### CODE REVIEW

**Review by rsetaluri — APPROVED** [review]

**Comment by rsetaluri** [comment]
Actually, let's make skip hashing a member variable so that we can just have it once and then be used by all of these functions

**Review by rsetaluri — CHANGES_REQUESTED** [review]
Actually, let's make skip hashing a member variable so that we can just have it once and then be used by all of these functions

**Comment by Kuree** [comment]
What do you mean member variable. Can you give me a concrete example?

**Comment by rsetaluri** [comment]
Like in `__init__` of `Generator` class there is `self.__skip_hashing = False`, and then `Generator` has function like

```python
def set_skip_hash(self, value=True):
    self.__skip_hashing = value
```

Then in all the functions where you take in `skip_hash` just use `self.__skip_hashing`.

**Comment by Kuree** [comment]
I see. That sounds good. I will refactor that.

**Review by rsetaluri — APPROVED** [review]

**Pull request merged**
