### PR TITLE
update magma IO syntax

### PR DESCRIPTION
**Pull request by hofstee**

### CODE REVIEW

**Comment by hofstee** [comment]
@rsetaluri I think the gold files need to be updated and then that's it.

**Comment by hofstee** [comment]
uhhhhhh not sure what's up with GarnetFlow

**Comment by hofstee** [comment]
Ok I don't think those GarnetFlow errors are from this PR. GarnetFlow is failing its scheduled builds with the same errors. I think this is ready to merge. @kuree

**Comment by rsetaluri** [comment]
@hofstee yeah this looks good. looks like peak/lassen errors, I pinged those guys

**Review by rsetaluri — APPROVED** [review]

**Comment by rsetaluri** [comment]
@hofstee looks like garnetflow is passing, feel free to merge

**Pull request merged**
