### PR TITLE
Pipelined wire

### PR DESCRIPTION
**Pull request by alexcarsello**
Adds new pass to pipeline a wire between two ports.

### CODE REVIEW

**Comment by Kuree** [comment]
Maybe just use `FromMagma`?

**Comment by alexcarsello** [comment]
I tried that but you can't do that because the magma Register primitive can't be used outside of a Magma circuit definition... it causes an error

**Comment by Kuree** [comment]
This is what I did. It requires mantle for some reason: 

https://github.com/StanfordAHA/canal/blob/aaacbccb9f84bb235afa19d30fe5d4192339aa7b/canal/circuit.py#L328-L329

Hopefully this helps.

**Comment by alexcarsello** [comment]
That doesn't work for this use case either. I want to parameterize by port type, not port width because I want to support more complex types than Bit/Bits (ConfigurationType for example). I'm pretty sure what I've done is the best way to do that generally.

**Review by rsetaluri — APPROVED** [review]

**Pull request merged**
